# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PbaThings', [dirname(__file__)])
        except ImportError:
            import _PbaThings
            return _PbaThings
        if fp is not None:
            try:
                _mod = imp.load_module('_PbaThings', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _PbaThings = swig_import_helper()
    del swig_import_helper
else:
    import _PbaThings
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PbaThings.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _PbaThings.SwigPyIterator_value(self)
    def incr(self, n=1): return _PbaThings.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _PbaThings.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _PbaThings.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _PbaThings.SwigPyIterator_equal(self, *args)
    def copy(self): return _PbaThings.SwigPyIterator_copy(self)
    def next(self): return _PbaThings.SwigPyIterator_next(self)
    def __next__(self): return _PbaThings.SwigPyIterator___next__(self)
    def previous(self): return _PbaThings.SwigPyIterator_previous(self)
    def advance(self, *args): return _PbaThings.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _PbaThings.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _PbaThings.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _PbaThings.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _PbaThings.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _PbaThings.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _PbaThings.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _PbaThings.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def iterator(self): return _PbaThings.StringArray_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _PbaThings.StringArray___nonzero__(self)
    def __bool__(self): return _PbaThings.StringArray___bool__(self)
    def __len__(self): return _PbaThings.StringArray___len__(self)
    def pop(self): return _PbaThings.StringArray_pop(self)
    def __getslice__(self, *args): return _PbaThings.StringArray___getslice__(self, *args)
    def __setslice__(self, *args): return _PbaThings.StringArray___setslice__(self, *args)
    def __delslice__(self, *args): return _PbaThings.StringArray___delslice__(self, *args)
    def __delitem__(self, *args): return _PbaThings.StringArray___delitem__(self, *args)
    def __getitem__(self, *args): return _PbaThings.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _PbaThings.StringArray___setitem__(self, *args)
    def append(self, *args): return _PbaThings.StringArray_append(self, *args)
    def empty(self): return _PbaThings.StringArray_empty(self)
    def size(self): return _PbaThings.StringArray_size(self)
    def clear(self): return _PbaThings.StringArray_clear(self)
    def swap(self, *args): return _PbaThings.StringArray_swap(self, *args)
    def get_allocator(self): return _PbaThings.StringArray_get_allocator(self)
    def begin(self): return _PbaThings.StringArray_begin(self)
    def end(self): return _PbaThings.StringArray_end(self)
    def rbegin(self): return _PbaThings.StringArray_rbegin(self)
    def rend(self): return _PbaThings.StringArray_rend(self)
    def pop_back(self): return _PbaThings.StringArray_pop_back(self)
    def erase(self, *args): return _PbaThings.StringArray_erase(self, *args)
    def __init__(self, *args): 
        this = _PbaThings.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _PbaThings.StringArray_push_back(self, *args)
    def front(self): return _PbaThings.StringArray_front(self)
    def back(self): return _PbaThings.StringArray_back(self)
    def assign(self, *args): return _PbaThings.StringArray_assign(self, *args)
    def resize(self, *args): return _PbaThings.StringArray_resize(self, *args)
    def insert(self, *args): return _PbaThings.StringArray_insert(self, *args)
    def reserve(self, *args): return _PbaThings.StringArray_reserve(self, *args)
    def capacity(self): return _PbaThings.StringArray_capacity(self)
    __swig_destroy__ = _PbaThings.delete_StringArray
    __del__ = lambda self : None;
StringArray_swigregister = _PbaThings.StringArray_swigregister
StringArray_swigregister(StringArray)

LEAP_FROG = _PbaThings.LEAP_FROG
SIX_ORDER = _PbaThings.SIX_ORDER
class TriangleCollisionThing(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TriangleCollisionThing, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TriangleCollisionThing, name)
    __repr__ = _swig_repr
    def __init__(self, nam="TriangleCollisionThing"): 
        this = _PbaThings.new_TriangleCollisionThing(nam)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PbaThings.delete_TriangleCollisionThing
    __del__ = lambda self : None;
    def Init(self, *args): return _PbaThings.TriangleCollisionThing_Init(self, *args)
    def Reset(self): return _PbaThings.TriangleCollisionThing_Reset(self)
    def solve(self): return _PbaThings.TriangleCollisionThing_solve(self)
    def Display(self): return _PbaThings.TriangleCollisionThing_Display(self)
    def Keyboard(self, *args): return _PbaThings.TriangleCollisionThing_Keyboard(self, *args)
    def Usage(self): return _PbaThings.TriangleCollisionThing_Usage(self)
TriangleCollisionThing_swigregister = _PbaThings.TriangleCollisionThing_swigregister
TriangleCollisionThing_swigregister(TriangleCollisionThing)


def TriangleCollision():
  return _PbaThings.TriangleCollision()
TriangleCollision = _PbaThings.TriangleCollision
class unitTestThing(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, unitTestThing, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, unitTestThing, name)
    __repr__ = _swig_repr
    def __init__(self, nam="unitTest"): 
        this = _PbaThings.new_unitTestThing(nam)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PbaThings.delete_unitTestThing
    __del__ = lambda self : None;
    def Init(self, *args): return _PbaThings.unitTestThing_Init(self, *args)
    def testBaseSolver(self): return _PbaThings.unitTestThing_testBaseSolver(self)
    def testSolver(self): return _PbaThings.unitTestThing_testSolver(self)
unitTestThing_swigregister = _PbaThings.unitTestThing_swigregister
unitTestThing_swigregister(unitTestThing)


def unitTest():
  return _PbaThings.unitTest()
unitTest = _PbaThings.unitTest
# This file is compatible with both classic and new-style classes.


