# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PbaViewer', [dirname(__file__)])
        except ImportError:
            import _PbaViewer
            return _PbaViewer
        if fp is not None:
            try:
                _mod = imp.load_module('_PbaViewer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _PbaViewer = swig_import_helper()
    del swig_import_helper
else:
    import _PbaViewer
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PbaViewer.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _PbaViewer.SwigPyIterator_value(self)
    def incr(self, n=1): return _PbaViewer.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _PbaViewer.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _PbaViewer.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _PbaViewer.SwigPyIterator_equal(self, *args)
    def copy(self): return _PbaViewer.SwigPyIterator_copy(self)
    def next(self): return _PbaViewer.SwigPyIterator_next(self)
    def __next__(self): return _PbaViewer.SwigPyIterator___next__(self)
    def previous(self): return _PbaViewer.SwigPyIterator_previous(self)
    def advance(self, *args): return _PbaViewer.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _PbaViewer.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _PbaViewer.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _PbaViewer.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _PbaViewer.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _PbaViewer.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _PbaViewer.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _PbaViewer.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def iterator(self): return _PbaViewer.StringArray_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _PbaViewer.StringArray___nonzero__(self)
    def __bool__(self): return _PbaViewer.StringArray___bool__(self)
    def __len__(self): return _PbaViewer.StringArray___len__(self)
    def pop(self): return _PbaViewer.StringArray_pop(self)
    def __getslice__(self, *args): return _PbaViewer.StringArray___getslice__(self, *args)
    def __setslice__(self, *args): return _PbaViewer.StringArray___setslice__(self, *args)
    def __delslice__(self, *args): return _PbaViewer.StringArray___delslice__(self, *args)
    def __delitem__(self, *args): return _PbaViewer.StringArray___delitem__(self, *args)
    def __getitem__(self, *args): return _PbaViewer.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _PbaViewer.StringArray___setitem__(self, *args)
    def append(self, *args): return _PbaViewer.StringArray_append(self, *args)
    def empty(self): return _PbaViewer.StringArray_empty(self)
    def size(self): return _PbaViewer.StringArray_size(self)
    def clear(self): return _PbaViewer.StringArray_clear(self)
    def swap(self, *args): return _PbaViewer.StringArray_swap(self, *args)
    def get_allocator(self): return _PbaViewer.StringArray_get_allocator(self)
    def begin(self): return _PbaViewer.StringArray_begin(self)
    def end(self): return _PbaViewer.StringArray_end(self)
    def rbegin(self): return _PbaViewer.StringArray_rbegin(self)
    def rend(self): return _PbaViewer.StringArray_rend(self)
    def pop_back(self): return _PbaViewer.StringArray_pop_back(self)
    def erase(self, *args): return _PbaViewer.StringArray_erase(self, *args)
    def __init__(self, *args): 
        this = _PbaViewer.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _PbaViewer.StringArray_push_back(self, *args)
    def front(self): return _PbaViewer.StringArray_front(self)
    def back(self): return _PbaViewer.StringArray_back(self)
    def assign(self, *args): return _PbaViewer.StringArray_assign(self, *args)
    def resize(self, *args): return _PbaViewer.StringArray_resize(self, *args)
    def insert(self, *args): return _PbaViewer.StringArray_insert(self, *args)
    def reserve(self, *args): return _PbaViewer.StringArray_reserve(self, *args)
    def capacity(self): return _PbaViewer.StringArray_capacity(self)
    __swig_destroy__ = _PbaViewer.delete_StringArray
    __del__ = lambda self : None;
StringArray_swigregister = _PbaViewer.StringArray_swigregister
StringArray_swigregister(StringArray)

class PbaViewer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PbaViewer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PbaViewer, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["Instance"] = lambda x: _PbaViewer.PbaViewer_Instance
    if _newclass:Instance = staticmethod(_PbaViewer.PbaViewer_Instance)
    __swig_destroy__ = _PbaViewer.delete_PbaViewer
    __del__ = lambda self : None;
    def Init(self, *args): return _PbaViewer.PbaViewer_Init(self, *args)
    def MainLoop(self): return _PbaViewer.PbaViewer_MainLoop(self)
    def SetWidth(self, *args): return _PbaViewer.PbaViewer_SetWidth(self, *args)
    def SetHeight(self, *args): return _PbaViewer.PbaViewer_SetHeight(self, *args)
    def GetWidth(self): return _PbaViewer.PbaViewer_GetWidth(self)
    def GetHeight(self): return _PbaViewer.PbaViewer_GetHeight(self)
    def SetTitle(self, *args): return _PbaViewer.PbaViewer_SetTitle(self, *args)
    def GetTitle(self): return _PbaViewer.PbaViewer_GetTitle(self)
    def Display(self): return _PbaViewer.PbaViewer_Display(self)
    def Keyboard(self, *args): return _PbaViewer.PbaViewer_Keyboard(self, *args)
    def Mouse(self, *args): return _PbaViewer.PbaViewer_Mouse(self, *args)
    def Motion(self, *args): return _PbaViewer.PbaViewer_Motion(self, *args)
    def Special(self, *args): return _PbaViewer.PbaViewer_Special(self, *args)
    def Idle(self): return _PbaViewer.PbaViewer_Idle(self)
    def Reshape(self, *args): return _PbaViewer.PbaViewer_Reshape(self, *args)
    def Reset(self): return _PbaViewer.PbaViewer_Reset(self)
    def Home(self): return _PbaViewer.PbaViewer_Home(self)
    def AddThing(self, *args): return _PbaViewer.PbaViewer_AddThing(self, *args)
    def Usage(self): return _PbaViewer.PbaViewer_Usage(self)
PbaViewer_swigregister = _PbaViewer.PbaViewer_swigregister
PbaViewer_swigregister(PbaViewer)

def PbaViewer_Instance():
  return _PbaViewer.PbaViewer_Instance()
PbaViewer_Instance = _PbaViewer.PbaViewer_Instance


def CreateViewer():
  return _PbaViewer.CreateViewer()
CreateViewer = _PbaViewer.CreateViewer
# This file is compatible with both classic and new-style classes.


