# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_PbaHou', [dirname(__file__)])
        except ImportError:
            import _PbaHou
            return _PbaHou
        if fp is not None:
            try:
                _mod = imp.load_module('_PbaHou', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _PbaHou = swig_import_helper()
    del swig_import_helper
else:
    import _PbaHou
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PbaHou.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _PbaHou.SwigPyIterator_value(self)
    def incr(self, n=1): return _PbaHou.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _PbaHou.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _PbaHou.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _PbaHou.SwigPyIterator_equal(self, *args)
    def copy(self): return _PbaHou.SwigPyIterator_copy(self)
    def next(self): return _PbaHou.SwigPyIterator_next(self)
    def __next__(self): return _PbaHou.SwigPyIterator___next__(self)
    def previous(self): return _PbaHou.SwigPyIterator_previous(self)
    def advance(self, *args): return _PbaHou.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _PbaHou.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _PbaHou.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _PbaHou.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _PbaHou.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _PbaHou.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _PbaHou.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _PbaHou.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def iterator(self): return _PbaHou.StringArray_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _PbaHou.StringArray___nonzero__(self)
    def __bool__(self): return _PbaHou.StringArray___bool__(self)
    def __len__(self): return _PbaHou.StringArray___len__(self)
    def pop(self): return _PbaHou.StringArray_pop(self)
    def __getslice__(self, *args): return _PbaHou.StringArray___getslice__(self, *args)
    def __setslice__(self, *args): return _PbaHou.StringArray___setslice__(self, *args)
    def __delslice__(self, *args): return _PbaHou.StringArray___delslice__(self, *args)
    def __delitem__(self, *args): return _PbaHou.StringArray___delitem__(self, *args)
    def __getitem__(self, *args): return _PbaHou.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _PbaHou.StringArray___setitem__(self, *args)
    def append(self, *args): return _PbaHou.StringArray_append(self, *args)
    def empty(self): return _PbaHou.StringArray_empty(self)
    def size(self): return _PbaHou.StringArray_size(self)
    def clear(self): return _PbaHou.StringArray_clear(self)
    def swap(self, *args): return _PbaHou.StringArray_swap(self, *args)
    def get_allocator(self): return _PbaHou.StringArray_get_allocator(self)
    def begin(self): return _PbaHou.StringArray_begin(self)
    def end(self): return _PbaHou.StringArray_end(self)
    def rbegin(self): return _PbaHou.StringArray_rbegin(self)
    def rend(self): return _PbaHou.StringArray_rend(self)
    def pop_back(self): return _PbaHou.StringArray_pop_back(self)
    def erase(self, *args): return _PbaHou.StringArray_erase(self, *args)
    def __init__(self, *args): 
        this = _PbaHou.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _PbaHou.StringArray_push_back(self, *args)
    def front(self): return _PbaHou.StringArray_front(self)
    def back(self): return _PbaHou.StringArray_back(self)
    def assign(self, *args): return _PbaHou.StringArray_assign(self, *args)
    def resize(self, *args): return _PbaHou.StringArray_resize(self, *args)
    def insert(self, *args): return _PbaHou.StringArray_insert(self, *args)
    def reserve(self, *args): return _PbaHou.StringArray_reserve(self, *args)
    def capacity(self): return _PbaHou.StringArray_capacity(self)
    __swig_destroy__ = _PbaHou.delete_StringArray
    __del__ = lambda self : None;
StringArray_swigregister = _PbaHou.StringArray_swigregister
StringArray_swigregister(StringArray)

class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _PbaHou.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PbaHou.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _PbaHou.floatArray___getitem__(self, *args)
    def __setitem__(self, *args): return _PbaHou.floatArray___setitem__(self, *args)
    def cast(self): return _PbaHou.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _PbaHou.floatArray_frompointer
    if _newclass:frompointer = staticmethod(_PbaHou.floatArray_frompointer)
floatArray_swigregister = _PbaHou.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(*args):
  return _PbaHou.floatArray_frompointer(*args)
floatArray_frompointer = _PbaHou.floatArray_frompointer

class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _PbaHou.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _PbaHou.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _PbaHou.doubleArray___getitem__(self, *args)
    def __setitem__(self, *args): return _PbaHou.doubleArray___setitem__(self, *args)
    def cast(self): return _PbaHou.doubleArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _PbaHou.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_PbaHou.doubleArray_frompointer)
doubleArray_swigregister = _PbaHou.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args):
  return _PbaHou.doubleArray_frompointer(*args)
doubleArray_frompointer = _PbaHou.doubleArray_frompointer

class PbaHouParticles(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PbaHouParticles, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PbaHouParticles, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["Instance"] = lambda x: _PbaHou.PbaHouParticles_Instance
    if _newclass:Instance = staticmethod(_PbaHou.PbaHouParticles_Instance)
    __swig_destroy__ = _PbaHou.delete_PbaHouParticles
    __del__ = lambda self : None;
    def init(self, *args): return _PbaHou.PbaHouParticles_init(self, *args)
    def solve(self): return _PbaHou.PbaHouParticles_solve(self)
    def advect(self, *args): return _PbaHou.PbaHouParticles_advect(self, *args)
    def test(self, *args): return _PbaHou.PbaHouParticles_test(self, *args)
    def add_DS(self, *args): return _PbaHou.PbaHouParticles_add_DS(self, *args)
    def set_pos(self, *args): return _PbaHou.PbaHouParticles_set_pos(self, *args)
    def set_vel(self, *args): return _PbaHou.PbaHouParticles_set_vel(self, *args)
    def set_dt(self, *args): return _PbaHou.PbaHouParticles_set_dt(self, *args)
    def set_gravity(self, *args): return _PbaHou.PbaHouParticles_set_gravity(self, *args)
    def set_current_frame(self, *args): return _PbaHou.PbaHouParticles_set_current_frame(self, *args)
    def get_pos(self, *args): return _PbaHou.PbaHouParticles_get_pos(self, *args)
    def get_vel(self, *args): return _PbaHou.PbaHouParticles_get_vel(self, *args)
    def get_nb(self): return _PbaHou.PbaHouParticles_get_nb(self)
    def reset(self): return _PbaHou.PbaHouParticles_reset(self)
PbaHouParticles_swigregister = _PbaHou.PbaHouParticles_swigregister
PbaHouParticles_swigregister(PbaHouParticles)

def PbaHouParticles_Instance():
  return _PbaHou.PbaHouParticles_Instance()
PbaHouParticles_Instance = _PbaHou.PbaHouParticles_Instance


def CreatePbaHouParticles():
  return _PbaHou.CreatePbaHouParticles()
CreatePbaHouParticles = _PbaHou.CreatePbaHouParticles
# This file is compatible with both classic and new-style classes.


